### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by PorridgePower** [harvard-acc/gem5-aladdin#16]
Appears while executing __to_nodes(self)

**Comment by xyzsam** [comment]
I will need a lot more information than this if you want me to look into it:

1. How high is the memory usage? Is it a sudden peak that causes the simulation to run out of memory or is it a sustained usage?
2. `__to_nodes(self)` alone isn't enough to diagnose an issue. I need a callstack.
3. What are you trying to simulate? How much simulated DRAM? etc
4. How much memory do you have on your host machine?
