### ISSUE TITLE
Docker pull problem

### ISSUE THREAD

**Issue by yangyl7239** [harvard-acc/gem5-aladdin#17]
Using default tag: latest
latest: Pulling from xyzsam/gem5-aladdin
34667c7e4631: Pull complete 
d18d76a881a4: Pull complete 
119c7358fbfc: Pull complete 
2aaf13f3eff0: Pull complete 
d6b6c17dc2be: Pull complete 
39cd4d0c35bb: Pull complete 
d3671fc2b01c: Pull complete 
16f31d567feb: Pull complete 
7626505b6474: Pull complete 
a70da26685ea: Pull complete 
b30642ff8ef6: Extracting  10.56GB/10.56GB
22ab926116f1: Download complete 
c9cfe83b14f9: Download complete 
bfa5f9231501: Download complete 
a20900fd9e01: Download complete 
5cd15bb32aec: Download complete 
eea7b62d6dbc: Download complete 
8644728c092c: Download complete 
latest: Pulling from xyzsam/gem5-aladdin
34667c7e4631: Downloading  7.105MB/43.56MB
d18d76a881a4: Pulling fs layer 
119c7358fbfc: Download complete 
2aaf13f3eff0: Download complete 
d6b6c17dc2be: Downloading  7.506MB/189.2MB
39cd4d0c35bb: Waiting 
d3671fc2b01c: Waiting 
16f31d567feb: Waiting 
7626505b6474: Waiting 
a70da26685ea: Waiting 
b30642ff8ef6: Waiting 
22ab926116f1: Waiting 
c9cfe83b14f9: Waiting 
bfa5f9231501: Waiting 
a20900fd9e01: Waiting 
5cd15bb32aec: Waiting 
eea7b62d6dbc: Waiting 
8644728c092c: Waiting 
--------------------------------------------------------------------------------------------------------------
Using Docker Image, pull is resumed immediately after pulling once, but the docker images command cannot find the container that was pulled down.

**Comment by xyzsam** [comment]
It sounds like the docker pull failed, otherwise it should show up.

**Comment by yangyl7239** [comment]
1
