### ISSUE TITLE
Error: can't find library python2.7 required by python

### ISSUE THREAD

**Issue by majid169** [harvard-acc/gem5-aladdin#2]
Hi,

I am getting this error while compiling the source:
Error: can't find library python2.7 required by python
I have Python2.7 and Python-dev,a nd SQLlite  installed. I can compile the latest version of gem5 on my machine, but I cannot install aladdin.

**Comment by majid169** [comment]
Boost was the problem. Just to record, you can check log file in build directory to find the reason.

**Comment by gaurav-1993singh** [comment]
Hi,
Is this issue fixed? I have been trying to get around this issue without any luck. 
Error: can't find library python2.7 required by python
In the scons_config.log, it says the following:
/usr/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
Am I doing something wrong here?

**Comment by xyzsam** [comment]
This should have been fixed in the latest push. Please pull HEAD and try again.

**Comment by gaurav-1993singh** [comment]
That worked! Thanks!
