### ISSUE TITLE
How to build gem5 on Linux?

### ISSUE THREAD

**Issue by peterhchen** [harvard-acc/gem5-aladdin#41]
How to build gem5 on Linux? In my case, it is in Secure zone with default Python 2.7.
scons only have > 3.0. I have to reset the system python (2.7 into 3.0+) Attached ppt is step-by-step with image capture for both Ubuntu and python 2.6 terminal . 
[052_BuildRun_Gem5_Dependency_RedZone.pptx](https://github.com/harvard-acc/gem5-aladdin/files/7471224/052_BuildRun_Gem5_Dependency_RedZone.pptx)
).

**Comment by xyzsam** [comment]
What problem are you experiencing? 

I'd like to reiterate how bug reports should be filed: they should actually describe a bug or problem, and they should include instructions on how to reproduce. Attaching a powerpoint is not a recommended way to file these reports - and in any case, I looked at the attached ppt and it does not answer either of these two questions. Please refrain from attaching powerpoints in the future - they are cumbersome to open, pose security risks to us, and are inefficient in communicating bugs too.

**Comment by xyzsam** [comment]
Closing this issue as #42 has more details.
