### ISSUE TITLE
GEMM in Systolic Array

### ISSUE THREAD

**Issue by mateo-vm** [harvard-acc/gem5-aladdin#46]
Is there currently a way to compute matrix-matrix multiplications with the systolic array or is it limited to convolutional tensors?

**Comment by yaoyuannnn** [comment]
You can run GEMMs on the systolic array as special convolutions. For example, an FC of (M, K) * (K, N) can be viewed as a 1x1 convolution of (1, M, 1, K) and (N, 1, 1, K), which produces a (1, M, 1, N) tensor.

**Comment by mateo-vm** [comment]
Thank you for the reply. There were some errors (in line with #43), but in general it worked.

In case someone else want to test this too, just note that it is needed to set up the stride and the padding accordingly.
