### ISSUE TITLE
Incorrect path to misc.hh

### ISSUE THREAD

**Issue by hoangt** [harvard-acc/gem5-aladdin#5]
In src/aladdin/gem5/HybridDatapath.cpp, line 11: 
#include "base/misc.hh"  -->   #include "arch/x86/regs/misc.hh"

**Comment by xyzsam** [comment]
You seem to be an older version of Aladdin. See this commit: https://github.com/ysshao/ALADDIN/commit/422713be97ad0aab90bc807306702196d2c6b1c8

**Comment by hoangt** [comment]
Thanks, I did not have the update code by running "git recursive"
